name: Deploy Nuxt to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: nuxt

      - name: Install dependencies
        run:  |
          # Удаляем только .nuxt node_modules package-lock.json
          rm -rf .nuxt node_modules package-lock.json
          # Стандартная установка с созданием package-lock.json
          npm install

      - name: Static HTML export with Nuxt
        run: |
          npm run generate
          echo "Build output:"
          ls -la .output/public || echo "No .output/public"
          ls -la dist || echo "No dist"

      - name: Try upload Nuxt 3 artifact
        continue-on-error: true
        run: |
          if [ -d ".output/public" ]; then
            echo "Uploading Nuxt 3 artifact from .output/public"
            cp -r .output/public dist
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Verify artifact
        run: |
          if [ ! -d "dist" ]; then
            echo "::error::No build output found in either .output/public or dist"
            exit 1
          fi

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4